# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sentinel2analyzer
                                 A QGIS plugin
 The plugin allows for managing Sentinel-2 data; computing multispectral indices; and making some statistical analysis.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-03
        copyright            : (C) 2025 by Chiara Bottaro, Thomas Martinoli
        email                : chiara.bottaro@polimi.it ; thomas.martinoli@polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sentinel2analyzer class from file sentinel2analyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sentinel2analyzer import sentinel2analyzer
    return sentinel2analyzer(iface)
